name: Release Mr. Hashemi

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.0.java8' 
    - run: java -version
    - uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn package

    - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'native/hashemi'
